Add styles for nested <ol> tags
helpscout/doc-article-styles pull request #14
Opened 2019-04-01 18:27 UTC by jgritman

We had a customer report [this issue](https://github.com/helpscout/beacon-ios-sdk/issues/30) against the iOS SDK, but it looks like all Beacon clients need this css to match the behavior of docs web. 

I'm not sure about the margins if someone from design could weigh in on those. Below is a screenshot of these changes applied to iOS.

![Screen Shot 2019-04-01 at 12 26 19 PM](https://user-images.githubusercontent.com/251711/55350481-727bc200-5479-11e9-8070-c3d68bf95f40.png)

Once we push the changes here, I'll write up cards for all Beacon clients to pull in the latest versions.

2019-04-01 18:28 UTC, jgritman commented
![](https://github.trello.services/images/mini-trello-icon.png) [List type for nested <ol> tags for articles](https://trello.com/c/ILoCkYuZ/373-list-type-for-nested-ol-tags-for-articles)

2019-04-01 18:29 UTC, ItsJonQ approved these changes
Oh dang!~ Double `ol`. Thanks for for the fix @jgritman !!

🚀 from me!

2019-04-01 20:39 UTC, digitaldesigner requested changes
Looks good, but it seems we've regressed on the hanging indent: https://trello.com/c/P2Lw629E/5-article-keep-a-hanging-indent-for-lists

2019-04-02 22:28 UTC, jgritman commented
@digitaldesigner I've re-added the changes so the list position is now `outside`:

![Screen Shot 2019-04-02 at 4 23 10 PM](https://user-images.githubusercontent.com/251711/55440204-2fe2e400-5564-11e9-8842-3efc8040885a.png)

2019-04-08 22:35 UTC, digitaldesigner approved these changes

2019-04-08 22:41 UTC, merged

2019-04-09 15:00 UTC, ItsJonQ commented
@jgritman I'll help make a release for this!